defmodule AshGqlSubBug.Repo.Migrations.AddTestResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:test_resources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :choice, :text
    end
  end

  def down do
    drop table(:test_resources)
  end
end
